version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/pixi-cjk

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: yarn install

      # Cache dependencies
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}
      
      # Upload codecov
      - codecov/upload:
          file: ./coverage/lcov.info

      # run build
      - run: yarn build

      # run tests
      - run: yarn test --coverage --ci --silent
      - run: yarn tsc
      - run: yarn lint

      # upload coverage report
      - run: yarn codecov
